import {
  Hexagon,
  Building,
  Building2,
  GitBranch,
  Bolt,
  Layers,
  FileCode,
  Server,
  Atom,
  Triangle,
  Box,
  Factory,
  Hammer,
  Cog,
  Copy,
  Database,
  Plug,
  Link as LinkIcon,
  Paintbrush,
  Warehouse,
  Feather,
  Shield,
  Terminal,
  Languages,
  Repeat,
  MessageSquare,
  Save,
  Eye,
  ToggleRight,
  Puzzle,
  FileText,
  Users,
  Wrench,
  Settings,
  Zap,
  Code,
} from 'lucide-react';
import type { ComponentType } from 'react';

const iconMap: Record<string, ComponentType<any>> = {
  hexagon: Hexagon,
  building: Building,
  'building-2': Building2,
  'git-branch': GitBranch,
  bolt: Bolt,
  layers: Layers,
  'file-code': FileCode,
  server: Server,
  atom: Atom,
  triangle: Triangle,
  box: Box,
  factory: Factory,
  hammer: Hammer,
  cog: Cog,
  copy: Copy,
  database: Database,
  plug: Plug,
  link: LinkIcon,
  paintbrush: Paintbrush,
  warehouse: Warehouse,
  feather: Feather,
  shield: Shield,
  terminal: Terminal,
  languages: Languages,
  repeat: Repeat,
  'message-square': MessageSquare,
  save: Save,
  eye: Eye,
  'toggle-right': ToggleRight,
  puzzle: Puzzle,
  'file-text': FileText,
  users: Users,
  tools: Wrench,
  settings: Settings,
  zap: Zap,
  code: Code,
  factory2: Factory,
  brush: Paintbrush,
  'puzzle-piece': Puzzle,
  'layer-group': Layers,
  'sync-alt': Repeat,
  redo: Repeat,
  comments: MessageSquare,
  'toggle-on': ToggleRight,
  industry: Factory,
};

export const getIconComponent = (name: string): ComponentType<any> => {
  return iconMap[name] || Cog;
};
